### ISSUE TITLE
Reconsider the default for codelens?

### ISSUE THREAD

**Issue by chenglou** [reasonml-editor/vscode-reasonml#182] opened 2018-03-09 07:47 UTC
From the discussions in discord it seems that folks are gradually favoring having codelens off by default because of the jumpiness issues (e.g. https://twitter.com/DmytroGladkyi/status/971875684325961728). I'm wondering if we should switch it off by default for now (and highlight it in README) until whichever plan we had to reduce jumpiness concretizes.

**Comment by freebroccolo** [comment] 2018-03-09 08:39
If someone wants to make a PR disabling the setting and updating the README I will merge it and publish a new version. I don't think it really needs to be on by default.

I'm not sure there is a good solution to fix the jumpiness in the extension though. I've tried a few things in the past and while they sometimes led to an improvement, they also introduced a lot more complexity and the potential for other weird bugs. This is something that really needs to be fixed by the vscode team somehow.

**Comment by gladimdim** [comment] 2018-03-09 09:04
@freebroccolo I made a PR to disable codelens by default: 
https://github.com/reasonml-editor/vscode-reasonml/pull/183

**Comment by tcoopman** [comment] 2018-03-09 20:25
I believe the F# codelens has an option to show the lens after the function line instead of above. This might solve the jumpiness?

**Comment by freebroccolo** [comment] 2018-03-11 21:24
I've merged the PR to disable this by default.

@tcoopman I don't see how having the codelens below the function definition line would make a difference. The problem is that all of the subsequent lines will still be shifted downward. The function definition line will also be shifted downward unless it is the first one in the file.

**Closed by freebroccolo** 2018-03-11 21:24 UTC
Labels: A-analysis, C-question, E-easy, S-investigating

**Comment by tcoopman** [comment] 2018-03-12 06:54
@freebroccolo, with after I meant next to the line. Not below it.
