### ISSUE TITLE
Support for connected rtop session.

### ISSUE THREAD

**Issue by abhi18av** [reasonml-editor/vscode-reasonml#43] opened 2017-03-05 11:17 UTC
Hi @freebroccolo 

So far the extension works like magic :+1:

I do have two issues,
1. How to compile `ReasonML` code from the editor? 
2. Are there any plans to add support for "send to repl" kind of funcionality?

**Comment by freebroccolo** [comment] 2017-03-07 03:13
Thanks for the feedback.

At the moment there is no builtin support for building projects from the editor. This is something I've been thinking about but there's a fair amount of complexity involved in doing it well, at least if the idea is to be able to support different build systems.

As far as repl integration is concerned, there are no concrete plans for it but I would like to add that at some point. It should not be too difficult to do it.

**Comment by abhi18av** [comment] 2017-03-07 03:14
@freebroccolo , looking forward to it :smile:

**Comment by freebroccolo** [comment] 2018-02-09 20:29
I've been thinking about the idea of REPL integration for awhile but (at least for now) I've decided against working on such a feature.

The problem is that REPL integration will never work well without support from the build system or quite a bit of manual intervention from the user (in order to load the right packages via topfind, etc). I don't think I could ever make it automatic enough to provide a good experience.

Given that, and given how usable the integrated terminal already is, it seems better to me to instead focus on providing a way to launch the REPL through the terminal via jbuilder or something like that. Maybe we could additionally have a command that would reload a module too (or watch for edits). But I don't think it makes sense to try do a more direct integration at this point.

I'm open to arguments as to why my suggested approach may not be enough but for now I'll close this.

**Closed by freebroccolo** 2018-02-09 20:29 UTC
Labels: A-tooling, C-feature-request, E-hard, P-low, S-wontfix
