### ISSUE TITLE
Merlin can't find any information if .merlin is not in the root.

### ISSUE THREAD

**Issue by arnarthor** [reasonml-editor/vscode-reasonml#76] opened 2017-06-19 10:53 UTC
I had a project where .merlin was in a sub folder which caused this to happen.

### Actual behavior
![image](https://user-images.githubusercontent.com/4514159/27281842-25119f50-54dd-11e7-9c5f-af8b369f004f.png)

### Expected behavior
Merlin should find build information despite .merlin being in a sub folder.

### Reproduction repo
https://github.com/kristinn93/FolfIceland/tree/50a18ec3192ad6286cfa5bbb63c3fd15adaea50c this commit for this project has the .merlin folder (and bsconfig.json) in the folder FolfApp instead of in the root. If you open the root project and open a Reason file there, it will annotate everything with red like the image above.

I don't know if this is a bug in reason-mode or not, but I figured it was since this project works fine in Emacs with emacs-reason-mode enabled.

**Comment by TheSpyder** [comment] 2017-07-07 06:41
This scenario is very common when using jbuilder, which creates `.merlin` files next to the `jbuild` files.

**Comment by jordwalke** [comment] 2017-07-07 10:12
I noticed this too. I wanted to try to fix this, but I couldn't find anywhere in the code where the `.merlin` file is assumed to be / not be in a particular place. Is this happening deeper in the ocaml language server?

**Comment by freebroccolo** [comment] 2017-07-07 18:52
@jordwalke pretty much everything except for the following is driven by the language server:

- some auto formatting and indentation behavior
- keybindings
- syntax highlighting

There are some commands implemented in this plugin which are separate from the server but they basically just amount to custom rpc messages which the server understands how to respond to.

As for why this doesn't work, I'm not sure. I would expect that merlin would be able to find the correct `.merlin` relative to the source tree without any additional assistance from the server. However, it may be related to [this](https://github.com/freebroccolo/ocaml-language-server/pull/25).

@arnarthor When you are opening the file in the editor, how are you doing that? Are you opening the project root folder first (to where you can see the project folder at the root in the explorer panel) and then opening the file or are you just opening the file directly?

**Comment by jaredly** [comment] 2017-07-18 14:54
fwiw, atom has no problem with this configuration, so I don't think it's merlin's fault?

**Comment by jordwalke** [comment] 2017-07-21 05:45
Atom doesn't use the language server (unless someone changes things?)

**Comment by Khady** [comment] 2017-09-09 18:18
I tried with the latest version of the extension which is using the code from https://github.com/freebroccolo/ocaml-language-server/pull/25 and the problem is still present. I will create a bounty of 100$ if anyone is willing to work on this issue.

**Comment by freebroccolo** [comment] 2017-09-09 20:33
@Khady are you using the example project mentioned earlier in this thread or a different one? I'll take a look and see if I can figure out why it's still not working.

**Comment by Khady** [comment] 2017-09-09 23:26
I tried on another example because I was in the plane. I will try the one mentioned earlier tomorrow. Thanks for the reminder.

**Comment by Khady** [comment] 2017-09-10 22:58
I didn't manage the build the example project. So I tried with https://github.com/Khady/ocaml-junit, especially with the file `lib/junit.ml`.

Line 189 there is this line:

```            Junit_xml.property ~name:p.name ~value:p.value```

If I try to get the type or jump to the definition of `Junit_xml` or `property`, it doesn't work.

**Comment by fikriauliya** [comment] 2017-09-22 15:08
Encounter this issue as well on https://github.com/reasonml/ReasonNativeProject
Copying `.merlin` from `internal` folder to root folder solve...

**Comment by donut** [comment] 2017-10-11 16:19
I'm using jbuilder with a native OCaml project and vscode-ocaml has no issues figuring out the type info. But vscode-resaonml seems to only figure out some types and provides no error checking. Talking to people in the discord channel, they told me it was because jbuilder generates a .merlin file for each jbuild file instead of a single one in the root like bsb(-native).

**Comment by freebroccolo** [comment] 2017-11-09 08:42
Can folks check if this is resolved with `1.0.8`?

**Comment by donut** [comment] 2017-11-09 12:53
@freebroccolo As far as I can tell, it's working and it's beautiful. Thank you so much!

**Comment by freebroccolo** [comment] 2017-11-09 16:36
Thanks. I'll go ahead and close this then.

**Closed by freebroccolo** 2017-11-09 16:36 UTC
Labels: bug

**Comment by OlegLustenko** [comment] 2017-11-09 20:30
Oh wow it fixed!!

Hope to look on it. It will make integration in existing projects much easier
