### ISSUE TITLE
Need a way to restart Merlin

### ISSUE THREAD

**Issue by yminsky** [reasonml-editor/vscode-reasonml#154] opened 2018-01-05 13:38 UTC
There are a number of cases where Merlin gets confused and has stale information (for example, if it was started up before the .merlin file was generated, or at least in one case where I've seen where a file was deleted.) Also, I've seen some memory leak issues.

In these cases, it's good to have a way to bounce Merlin to get it back into a good state. The now deprecated OCaml plugin had a way to do this, and I think this plugin needs one too. Killing merlin from the shell doesn't really help, because there's no way of starting it back up as far as I can tell.

My present workaround is simply to bounce vscode itself.

**Comment by freebroccolo** [comment] 2018-01-05 21:23
Support for (automatically) restarting Merlin is coming in the next release of the language server. It was actually briefly available previously but was causing some problems for Bucklescript users so I had to temporarily disabled it.

Probably the most convenient way to restart Merlin currently is via the "Reload Window" command from the command palette (cmd+P).

**Comment by jchavarri** [comment] 2018-01-11 10:34
> It was actually briefly available previously but was causing some problems for Bucklescript users so I had to temporarily disabled it.

@freebroccolo didn't we re-enable it already? https://github.com/freebroccolo/ocaml-language-server/pull/79

**Comment by freebroccolo** [comment] 2018-01-12 02:11
Yes although I haven't made a new release of the server since then. I was planning to merge a bunch of stuff having to do with the refactored merlin support before making another release but it's taking longer than anticipated due to some subtle issues I've been encountering with the task scheduling.

I'll probably make an interim release just to get this issue wrapped up though.

**Comment by freebroccolo** [comment] 2018-01-28 08:17
This should be resolved in release `1.0.21`. I expect there will probably need to be some further adjustments to the algorithm that decides when to restart merlin but it should work okay for most projects now.

**Closed by freebroccolo** 2018-01-28 08:17 UTC

**Comment by freebroccolo** [comment] 2018-04-04 08:08
I just released a new version `1.0.34` which should further improve the auto-restart functionality for merlin. In particular, the restart happens on a debounced timer which watches changes to `.merlin` files and for activity in `_build`. This, in combination with some other recent bug fixes, should eliminate most of the cases were merlin would get confused with stale information and require a manual restart. @yminsky Do you think this is enough or would you still prefer to have a special command to force the restart (aside from reload window)?

**Comment by freebroccolo** [comment] 2018-04-04 08:10
Also, if you happen to find some reproducible memory leak issues, please let me know.

**Comment by jchavarri** [comment] 2018-04-04 09:46
@freebroccolo thanks! Do you think these improvements might help fixing the Atom issues that @alexfedoseev mentioned in https://github.com/freebroccolo/ocaml-language-server/issues/76#issuecomment-372177331? I think most of them were related to `bsb` and `merlin` both stepping on each other when writing / reading `.merlin` files.

**Comment by yminsky** [comment] 2018-04-05 00:54
This seems like a reasonable solution to me. If I run into problems beyond that, I'll bring it up here.

**Comment by freebroccolo** [comment] 2018-04-05 01:57
@jchavarri in principle it could. I'm not sure if the Atom client is sending the necessary file change notifications though.

This is one of the things that has been discussed previously—we currently rely on the editor to send these notifications. This is the approach the Microsoft folks recommend but most clients aren't doing this yet and it's not clear they will get there anytime soon (especially for emacs and vim). I would prefer to move the file watching into the server but that will probably not happen until the native OCaml rewrite starts.

The other issue is we might need to be watching more directories to have this work with `bsb`. What directories does it modify during build? Would we need to add `node_modules` to that list?

cc @jordwalke

**Comment by alexfedoseev** [comment] 2018-04-05 05:38
@freebroccolo @jchavarri I bumped deps of `atim-ide-reason` and changed few random things in my codebase: no `broken pipe` errors so far, I'll work for a few days w/ updated deps and report back if it's gone completely or not.
