### ISSUE TITLE
Go to definition uses absolute paths instead of relative

### ISSUE THREAD

**Issue by mqzry** [reasonml-editor/vscode-reasonml#121] opened 2017-10-21 09:33 UTC
When I try to use the GoTo functionality I get:

> Unable to open 'type.ml': File not found (file:///type.ml).

This file is actually at ./type.ml relative to the file I was at when using the GoTo.
Is this a known issue? Did I setup something wrong?

I use vanilla OCaml and just use this plugin because the old one is deprecated

**Comment by freebroccolo** [comment] 2017-10-21 11:17
From your description I'm not sure I understand what the problem is. Can you provide me with an actual project directory or repository or something and explain how this is happening in that context? Also, is this an issue that you have with `vscode-reasonml` but not the other `vscode-ocaml` extension?

**Comment by mqzry** [comment] 2017-10-21 11:38
Yes this is something that happens in vscode-reasonml and not in vscode-ocaml.

Repo: https://github.com/mqzry/bamboo

1. open src/ast/type.ml
2. GoTo on any function defined there
3. I get this error

**Comment by freebroccolo** [comment] 2017-11-12 22:20
This should be fixed in the current version of the extension. Please let me know if it's still not working.

**Closed by freebroccolo** 2017-11-12 22:20 UTC
