### ISSUE TITLE
Syntax coloring problems in OCaml code

### ISSUE THREAD

**Issue by modlfo** [reasonml-editor/vscode-reasonml#134] opened 2017-11-09 12:38 UTC
Now that hackwaly/vscode-ocaml is deprecated in favor of this plugin, I'm trying to make the switch but I have found many things that seems to me strange in the syntax coloring. I'm using Monokai, but many of these things happened in other themes.

- The content of strings in the form `{| text here |}` are colored. 
- The coloring of `let` and `let%bind` bindings are not consistent. Sometimes the inner `let` are the same color of the top level `let`.
- Some keywords like `rec` and `and` appear in a different color compared to the other keywords.
- Keywords like `of`, `end` and `struct` do not have any color.
- Things like `'a some` the `'a` gets the same color as keywords.

I hope you are aware of these issues and hopefully the OCaml code will look as nice as Reason code.

**Comment by freebroccolo** [comment] 2017-11-09 16:25
> The coloring of let and let%bind bindings are not consistent. Sometimes the inner let are the same color of the top level let.

Can you post a screenshot of this one?

**Comment by modlfo** [comment] 2017-11-09 16:37
Here's the code and a screenshot. I hope you can see it. In the first case is the `wrap @@` what changes the color. In the third `let` I don't know why is show in white instead.

```


let test () =
   wrap @@
   let%bind b = bar () in
   let x = foo b in
   x

let someFunction arg1 arg2 =
   match arg1 with
   | M.B ({ x } as r) -> M.B { r with x = arg2 :: x }
   | _ -> failwith ""

let otherFunction arg1 arg2 =
   match arg1 with
   | M.B r -> M.B { r with field = foo r.field arg2 }
   | _ -> failwith ""```

<img width="614" alt="screen shot 2017-11-09 at 18 33 32" src="https://user-images.githubusercontent.com/2001046/32617056-a66549f2-c57c-11e7-8bb8-608416d1efde.png">

**Comment by freebroccolo** [comment] 2017-11-09 16:48
I am probably not going to be able to fix the highlighting on this one:

```ocaml
let test () =
  wrap @@
  let%bind b = bar () in
  let x = foo b in
  x
```

The problem is we can't determine whether the `let` bindings that come after `wrap @@` are item-level or expression-level without scanning ahead multiple lines, and there is no way to do this in TextMate grammars.

You could either rewrite it like this:

```ocaml
let test () =
  let%bind b = bar () in
  let x = foo b in
  wrap x
```

or like this:

```ocaml
let test () =
  wrap begin
    let%bind b = bar () in
    let x = foo b in
    x
  end
```

The 3rd one looks like a bug that can be fixed.

**Comment by modlfo** [comment] 2017-11-09 17:00
What do you think about making all `let` the same color for the OCaml syntax?

**Comment by freebroccolo** [comment] 2017-11-09 18:55
I find the visual distinction useful and have no plans to change that part of the highlighting. However, I may still be able to get the example above to work by handling some operators (like `@@`) specially. I'm not sure yet.

**Comment by freebroccolo** [comment] 2017-11-10 00:05
The part where the 3rd `let` item loses highlighting should be fixed in release `1.0.9`.

**Comment by freebroccolo** [comment] 2017-11-10 01:10
Okay, both of the problems in your screenshot are fixed in `1.0.10`:

![fixed-opt](https://user-images.githubusercontent.com/151197/32637818-43261a72-c579-11e7-9d0d-86dc46d0fbb6.png)

**Comment by marco-m** [comment] 2018-01-08 17:47
@freebroccolo is there additional work that needs to be done or can this issue be closed ?

**Comment by freebroccolo** [comment] 2018-01-09 03:11
I think it can be closed. Thanks.

**Closed by freebroccolo** 2018-01-09 03:11 UTC

**Comment by marco-m** [comment] 2018-01-09 19:04
Thank you for vscode-reasonml ! :-)
