### ISSUE TITLE
Polymorphic local types break error reporting

### ISSUE THREAD

**Issue by quicksnap** [reasonml-editor/vscode-reasonml#79] opened 2017-06-29 01:48 UTC
Within a file that's working correctly, stick this somewhere in the middle:

`let foo: type a. a => a = fun a => a;`  (save the file)

Then change it to:

`let foo: type a b. a => a = fun a => a;`

After you save the file, you should see no errors. Now, elsewhere in the file, create some syntax errors. It seems error reporting stops working until you revert back to the first example with only one polymorphic type.

**Comment by Khady** [comment] 2017-07-04 10:08
I don't manage to reproduce this using master and the ocaml syntax.

Here is my file:

```ocaml
let test = 3

let toto = 3 + test

let foo : type a. a -> a = fun a -> a

let add1 = ( + ) 1
```

I then change it to this version and get an error

```ocaml
let test = 3

let toto = 3 + tes

let foo : type a b. a -> a = fun a -> a

let add1 = ( + ) 1
```

![image](https://user-images.githubusercontent.com/974142/27825894-9f4a3fc4-60a0-11e7-8aea-a882e9c16779.png)

And if I change it to this, I also have an error

```ocaml
let test 3

let toto = 3 + test

let foo : type a b. a -> a = fun a -> a

let add1 = ( + ) 1
```

![image](https://user-images.githubusercontent.com/974142/27825873-8d96018c-60a0-11e7-934f-817d52655182.png)

**Comment by quicksnap** [comment] 2017-07-04 17:04
I was using bucklescript to generate merlin. Perhaps that's the problem?

**Comment by quicksnap** [comment] 2017-07-04 17:05
I'll try your test code soon to see if I can replicate

**Comment by Khady** [comment] 2017-07-04 17:10
I'm not using any merlin file in this case. But it could indeed be because merlin is lost if you have something more complex in your file. Can you reproduce using another editor?

**Comment by freebroccolo** [comment] 2017-07-07 04:47
> I was using bucklescript to generate merlin. Perhaps that's the problem?

I believe there may be some problems with using the ocaml language server (which is what drives this plugin) with bucklescript but I haven't had a chance to do much testing for that recently. If you do manage to pinpoint what is causing it to fail though, please let me know.

**Comment by quicksnap** [comment] 2017-07-07 16:16
This isn't a big issue for me personally, but I just wanted to document. Maybe we should close, and I'll gather more info maybe?

**Comment by freebroccolo** [comment] 2017-07-07 17:32
Sounds fine. I'll go ahead and close it for now then.

**Closed by freebroccolo** 2017-07-07 17:32 UTC
