### ISSUE TITLE
Overeager pipe insertion

### ISSUE THREAD

**Issue by glennsl** [reasonml-editor/vscode-reasonml#46] opened 2017-03-23 23:42 UTC
I've discovered several problems with it:
1. Enter after using a pipe operator will insert a pipe followed by a blank space on the new line, so you'll have to press backspace to remove the blank space before finishing the pipe operator.
2. It ignores semicolons and inserts a pipe on new lines anyway
3. With vim mode and the cursor positioned in the middle of a line that starts with a pipe, pressing "o" will insert a new line starting with a pipe. This is very unexpected, as "o" should always insert a blank line.

I think there's more, but they've slipped my mind. I'll update this when I come across them.

**Comment by freebroccolo** [comment] 2017-03-23 23:59
> Enter after using a pipe operator will insert a pipe followed by a blank space on the new line, so you'll have to press backspace to remove the blank space before finishing the pipe operator.

Can you provide a concrete example for this along with what you expect to happen? The particulars of when `|` get inserted are determined by the rules you can find [here](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/extension.ts#L11).

> With vim mode and the cursor positioned in the middle of a line that starts with a pipe, pressing "o" will insert a new line starting with a pipe. This is very unexpected, as "o" should always insert a blank line.

I'm not sure I can fix this one. The problem is that the `onEnterRules` are handled by the editor widget and not by any logic that I control directly in this extension. There's also no direct interaction between this extension and the vim mode. However, it might be possible for the maintainers of the vim mode to somehow disable (or otherwise compensate for) `onEnterRules` (for all extensions) for that command.

**Comment by glennsl** [comment] 2017-03-24 10:32
Example for 1:

```reason
/* Before pressing Enter (cursor at §)*/
foo
|> doSomething§

/* After pressing Enter */
foo
|> doSomething
| §

/* Expected */
foo
|> doSomething
|> §
```
I think I'd actually prefer it not to insert anything at the end (for onEnterRules in general), but I like that it does insert when I press enter in the middle of a chain.

> However, it might be possible for the maintainers of the vim mode to somehow disable (or otherwise compensate for) onEnterRules (for all extensions) for that command.

I'm actually writing a kakooune mode for vscode, and will come across this issue myself. This might be very hard to fix due to the limitations of vscode, but if I do manage to fix it I'll upstream to vim mode.

Is it possible to have an option for this?

**Comment by glennsl** [comment] 2017-03-24 13:38
Here's another example of unexpected behaviour:

Before:
```
  doStuff
  |> Promise.then_§(fun x => 
```

After:
```
  doStuff
  |> Promise.then_
  | §(fun x => 
```

Expected
```
  doStuff
  |> Promise.then_
    §(fun x => 
```

**Comment by freebroccolo** [comment] 2017-03-24 17:31
> Example for 1:

Thanks. It should be possible to fix this and some of the other examples.

> I think I'd actually prefer it not to insert anything at the end (for onEnterRules in general), but I like that it does insert when I press enter in the middle of a chain.

The tricky part with this is that it's sort of difficult to be able to tell where the end of a block is just with the regex matching that is associated with `onEnterRules`.

There is a more powerful and more flexible alternative to `onEnterRules` which is to use the format-on-edit API that is available for language servers. This is something I've wanted to move towards in the long run anyway but it would take more effort to get similar basic functionality with that approach. However, with format-on-edit it would be possible to use a proper parser which would allow for much more accurate rules without all the corner cases.

> Is it possible to have an option for this?

As far as I know it is possible to disable the use of `onEnterRules` through an option at least not through the public editor APIs. To be honest I'm really not even sure there's much the vim people can do about this aside from maybe trying to compensate for unexpected output after the edit for a newline. Unfortunately, even though that might work it'd still be a bit of a hack.

I think it would be worthwhile for the vscode people make an option for this but I don't know if anyone has asked them for that or not.

This is another reason why the format-on-edit approach would be superior because that *would* be possible to disable with an option.

**Comment by freebroccolo** [comment] 2017-11-05 23:49
@glennsl Sorry for the delay on this. I think your examples should be fixed now. Let me know if there are still issues with it.

**Closed** 2017-11-05 23:48 UTC
Labels: bug
